@GameMarketAPIServer_HostAddress = https://localhost:7046/api/GameMarket

GET {{GameMarketAPIServer_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{GameMarketAPIServer_HostAddress}}/MergedGames
Accept: application/xmljson